login: &login
  username: cody
  password:
  adapter:  postgresql
  encoding: unicode
  pool: 5

development:
  <<: *login
  database: stringy_development

test:
  <<: *login
  database: stringy_test

production:
  <<: *login
  database: stringy_production
